name: api-ci
on:
  push:
    paths:
      - 'apps/api/**'
      - 'packages/**'
      - '.github/workflows/**'
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install API deps
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/api/requirements.txt
      - name: Import check
        run: python -c "import fastapi, httpx, sqlalchemy, pydantic; print('ok')"
